Traceback (most recent call last):
  File "/Users/arty/Downloads/penpal-english-main/penpal_english_bot.py", line 5, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
Traceback (most recent call last):
  File "/Users/arty/Downloads/penpal-english-main/penpal_english_bot.py", line 5, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
Traceback (most recent call last):
  File "/Users/arty/Downloads/penpal-english-main/penpal_english_bot.py", line 5, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
Traceback (most recent call last):
  File "/Users/arty/Downloads/penpal-english-main/penpal_english_bot.py", line 5, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
Traceback (most recent call last):
  File "/Users/arty/Downloads/penpal-english-main/penpal_english_bot.py", line 5, in <module>
    import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
